/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-sync-scripts */
import Head from "next/head";

/**
 * the head of the website
 *
 */
const HeadTag = () => {
    return (
        <Head>
            <title>Mustafa Alhasanat's Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="icons/logo.png" />
        </Head>
    );
};

export default HeadTag;
