import Head from "next/head";

/**
 * the head of the website
 *
 */
const HeadTag = () => {
    return (
        <Head>
            <title>Mustafa Alhasanat</title>
            <meta name="description" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
};

export default HeadTag;
