const LandingPageConstants = {
    avatarIons: [
        {
            id: "react-orbital-icon",
            src: String.raw`\icons\frameworks\reactIcon.png`,
            rotateZ: 60,
            rotateY: 80,
            delay: 0,
            shadow: "cyan",
        },
        {
            id: "angular-orbital-icon",
            src: String.raw`icons\frameworks\angularIcon.png`,
            rotateZ: 60,
            rotateY: 80,
            delay: 0.8,
            shadow: "red",
        },
        {
            id: "flutter-orbital-icon",
            src: String.raw`icons\frameworks\flutterIcon.png`,
            rotateZ: 60,
            rotateY: 80,
            delay: 1.6,
            shadow: "cyan",
        },
        {
            id: "github-orbital-icon",
            src: String.raw`icons\frameworks\nextIcon.png`,
            rotateZ: 60,
            rotateY: 80,
            delay: 2.4,
            shadow: "black",
        },
        {
            id: "node-orbital-icon",
            src: String.raw`icons\frameworks\nodeIcon.png`,
            rotateZ: -60,
            rotateY: 80,
            delay: 0.3,
            shadow: "green",
        },
        {
            id: "fastAPI-orbital-icon",
            src: String.raw`icons\frameworks\fastAPIIcon.png`,
            rotateZ: -60,
            rotateY: 80,
            delay: 1.1,
            shadow: "cyan",
        },
        {
            id: "docker-orbital-icon",
            src: String.raw`icons\tools\dockerIcon.png`,
            rotateZ: -60,
            rotateY: 80,
            delay: 1.9,
            shadow: "white",
        },
        {
            id: "django-orbital-icon",
            src: String.raw`icons\frameworks\djangoIcon.png`,
            rotateZ: -60,
            rotateY: 80,
            delay: 2.7,
            shadow: "white",
        },
        {
            id: "html-orbital-icon",
            src: String.raw`icons\languages\htmlIcon.png`,
            rotateZ: 0,
            rotateY: 80,
            delay: 0.6,
            shadow: "orange",
        },
        {
            id: "css-orbital-icon",
            src: String.raw`icons\languages\cssIcon.png`,
            rotateZ: 0,
            rotateY: 80,
            delay: 1.4,
            shadow: "lightblue",
        },
        {
            id: "js-orbital-icon",
            src: String.raw`icons\languages\jsIcon.png`,
            rotateZ: 0,
            rotateY: 80,
            delay: 2.2,
            shadow: "yellow",
        },
        {
            id: "python-orbital-icon",
            src: String.raw`icons\languages\pythonIcon.png`,
            rotateZ: 0,
            rotateY: 80,
            delay: 3,
            shadow: "blue",
        },
    ]
};

export default LandingPageConstants;